name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install gcc libexpat-dev libz-dev make
    - name: configure
      run: ./configure
    - name: make
      run: make newflasher.x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: newflasher.x64
        # A file, directory or wildcard pattern that describes what to upload
        path: newflasher
        if-no-files-found: error # optional, default is warn
        retention-days: 90 # optional
